import numpy as np

np_a = np.arange(1, 10).reshape(3, 3)
print(np_a)

print('sum:',np.sum(np_a))
print('sum(axis=0):',np.sum(np_a, axis=0))
sum_0 = np.sum(np_a, axis=1)
print('sum(axis=1):',sum_0, type(sum_0))
print('-' * 30)
print('prod:',np.prod(np_a))
print('prod(axis=0):',np.prod(np_a, axis=0))
print('prod(axis=1):',np.prod(np_a, axis=1))
print('-' * 30)
print('mean:',np.mean(np_a))
print('mean(axis=0):',np.mean(np_a, axis=0))
print('mean(axis=1):',np.mean(np_a, axis=1))
print('-' * 30)
print('min:',np.min(np_a))
print('min(axis=0):',np.min(np_a, axis=0))
print('min(axis=1):',np.min(np_a, axis=1))
print('-' * 30)
print('max:',np.max(np_a))
print('max(axis=0):',np.max(np_a, axis=0))
print('max(axis=1):',np.max(np_a, axis=1))